#!/usr/bin/env python3

import logging
from src.main import *
from lib.colors import red,red_bg,white,white_bg,green_bg,green,reset

if __name__ == '__main__':
    try:
        octosuite().on_start()
       
    except KeyboardInterrupt:
        logging.warning('Process interrupted with Ctrl+C')
        exit(f'\n{white}[{red} x {white}] Process interrupted with {red_bg}Ctrl+C{reset}')
        
    except Exception as e:
        logging.error(f'Session terminated on error: {e}')
        exit(f'\n{white}[{red} ! {white}] Session {red_bg}terminated{reset}{white} on error: {red}{e}{reset}')
