[project]
name = "octosuite"
version = "5.0.0"
description = "Terminal-based toolkit for GitHub data analysis."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Ritchie Mwewa", email = "hi@rly0nheart.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rich>=14.3.3",
    "questionary>=2.1.1",
    "pyfiglet>=1.0.4",
    "update-checker>=0.18.0",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Natural Language :: English"
]

[project.urls]
Homepage = "https://bellingcat.com"
Issues = "https://github.com/bellingcat/octosuite/issues"
Repository = "https://github.com/bellingcat/octosuite"

[project.optional-dependencies]
dev = [
    "black>=26.1.0",
]

[project.scripts]
octosuite = "octosuite.app.main:start_app"

[tool.uv]
package = true